version: '3.8'

services:
  # 1. 数据库
  mysql:
    image: mysql:8.0
    container_name: video_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: video_db
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  # 2. 消息队列 & 缓存
  redis:
    image: redis:6.2
    container_name: video_redis
    ports:
      - "6379:6379"

  # 3. 对象存储 (仿 AWS S3)
  minio:
    image: minio/minio
    container_name: video_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # API 端口
      - "9001:9001" # 控制台端口
    volumes:
      - ./data/minio:/data